# Run tests and deploy to https://walles.github.io/barnklocka2.

name: test-and-deploy
on: [push]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
          channel: 'stable'
      - run: flutter format --output=none --set-exit-if-changed lib/ test/
      - run: flutter analyze
      - run: flutter test

      # Deploy new main commits to Github pages
      - uses: bluefireteam/flutter-gh-pages@v7
        if: github.ref == 'refs/heads/main'
        with:
          baseHref: /barnklocka2/
